<?php
    return array(
        'account'              => 2,
        '_twig'                => 1,
        '_form'                => 1,
        'staticfiles'          => 1,
        'robots.txt'           => 1,
        'sitemap'              => 1,
        'public_login'         => 1,
        'public_lostpass'      => 1,
        'public_register'      => 1,
        'public_activate'      => 1,
        'public_users'         => 1,
        'public_users_friends' => 1,
        'account_login'        => 1,
        'account_logout'       => 1,
        'account_about'        => 1,
        'account_avatar'       => 1,
        'account_email'        => 1,
        'account_contact'      => 1,
        'admin'                => -1,
        'admin_user'           => 1,
    );
